[project]
name = "talk"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.97.1",
    "openai-agents>=0.2.3",
    "pydantic-ai[logfire]>=0.4.5",
    "python-dotenv>=1.1.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
